src/restaurant_app/reservation/models.py
import datetime
from dataclasses import dataclass

from ..restaurant.models import TableModel


@dataclass
class ReservationRequestModel:
    restaurant_id: int
    name: str
    num_people: int
    time_from: datetime.time
    time_until: datetime.time
    reservation_date: datetime.date


@dataclass
class ReservationModel:
    id: int
    number: str
    name: str
    num_people: int
    time_from: datetime.time
    time_until: datetime.time
    reservation_date: datetime.date
    reserved_table: TableModel

    def date_format(self) -> str:
        return self.reservation_date.strftime("%Y-%m-%d")

    def reservation_time_format(self) -> str:
        return f"{self.time_from.strftime("%H:%M")} - {self.time_until.strftime("%H:%M")}"

src/restaurant_app/reservation/forms.py
from datetime import date

from flask_wtf import FlaskForm
from wtforms import DateField, HiddenField, IntegerField, StringField, TimeField, ValidationError, validators

from ..shared.form_validators import Gt, Lt


def validate_positive_number(form, field):
    if int(field.data) <= 0:
        raise ValidationError("Please enter a correct number of people!")


def validate_max_people(form, field):
    if int(field.data) > 6:
        raise ValidationError("A reservation for more than 6 people is not possible!")


def date_current_or_future(form, field):
    if field.data < date.today():
        raise ValidationError("Cannot make reservations in the past!")


class ReservationForm(FlaskForm):
    restaurant_id = HiddenField("restaurant_id")
    h = HiddenField("h")
    name = StringField("Reservation name", [validators.DataRequired(), validators.Length(max=255)])
    num_people = IntegerField(
        "Number of people", [validators.DataRequired(), validate_positive_number, validate_max_people]
    )
    time_from = TimeField(
        "Time from",
        [validators.DataRequired(), Lt("time_until", message="'Time from' needs to be before 'Time until'")],
    )
    time_until = TimeField(
        "Time until",
        [validators.DataRequired(), Gt("time_from", message="'Time until' needs to be after 'Time from'")],
    )
    reservation_date = DateField("Reservation date", [validators.DataRequired(), date_current_or_future])

src/restaurant_app/reservation/views.py
from dependency_injector.wiring import Provide, inject
from flask import Blueprint, render_template, request

from ..auth.views import login_required
from ..infrastructure.cache import Cache
from ..infrastructure.container import Container
from ..infrastructure.logger import LOG
from ..restaurant.models import RestaurantModel
from ..restaurant.service import RestaurantService
from ..shared.hash import valid_hash_supplied
from ..shared.view_helpers import get_restaurants_from_cache, prepare_view_model, put_restaurants_to_cache
from .forms import ReservationForm
from .models import ReservationRequestModel
from .service import ReservationError, ReservationService

bp = Blueprint("reservation", __name__)


def restaurant_from_cache(cache: Cache, restaurant_id: int, restaurant_svc: RestaurantService) -> RestaurantModel:
    restaurants = get_restaurants_from_cache(cache)
    if restaurants is None or len(restaurants) == 0:
        # reload restaurant from DB
        restaurants = restaurant_svc.get_all()
        if restaurants is not None and len(restaurants) > 0:
            put_restaurants_to_cache(cache, restaurants)
        restaurant = restaurant_svc.get_by_id(restaurant_id)
    else:
        restaurant = next(filter(lambda x: x.id == restaurant_id, restaurants))
    return restaurant


@bp.get("/reservation")
@login_required
@inject
def index(
    restaurant_svc: RestaurantService = Provide[Container.restaurant_svc], cache: Cache = Provide[Container.cache]
):
    LOG.info("view reservation/index")
    restaurants = restaurant_svc.get_all()
    LOG.debug(f"got {len(restaurants)} restaurants")
    if restaurants is not None and len(restaurants) > 0:
        put_restaurants_to_cache(cache, restaurants)

    model_params = prepare_view_model(restaurants=restaurants)
    return render_template("reservation/index.html", **model_params)


@bp.get("/reservation/partial/~reservations")
@login_required
@inject
def partial_reservations(
    restaurant_svc: RestaurantService = Provide[Container.restaurant_svc],
    reservation_svc: ReservationService = Provide[Container.reservation_svc],
    cache: Cache = Provide[Container.cache],
):
    LOG.info("view reservation/partial_reservations")
    restaurant_id = request.args.get("restaurant_id", "")
    if restaurant_id is None or restaurant_id == "":
        return ""

    restaurant = restaurant_from_cache(cache, int(restaurant_id), restaurant_svc)
    reservations = reservation_svc.get_reservation_for_restaurant(restaurant_id)
    LOG.debug(f"got {len(reservations)} reservations")
    return render_template("reservation/partial/reservation.html", reservations=reservations, restaurant=restaurant)


@bp.get("/reservation/partial/~reservation-form")
@login_required
@inject
def partial_reservation_form(
    restaurant_svc: RestaurantService = Provide[Container.restaurant_svc], cache: Cache = Provide[Container.cache]
):
    LOG.info("view reservation/partial_reservation_form")
    restaurant_id = request.args.get("restaurant_id", "")
    restaurant_id_hash = request.args.get("h", "")
    valid_hash_supplied(restaurant_id, restaurant_id_hash)

    restaurant = restaurant_from_cache(cache, int(restaurant_id), restaurant_svc)
    form = ReservationForm(data={"restaurant_id": restaurant_id, "h": restaurant_id_hash})
    return render_template("reservation/partial/reservation_form.html", restaurant=restaurant, form=form)


@bp.post("/reservation/partial/~reservation-save")
@login_required
@inject
def save(
    restaurant_svc: RestaurantService = Provide[Container.restaurant_svc],
    reservation_svc: ReservationService = Provide[Container.reservation_svc],
    cache: Cache = Provide[Container.cache],
):
    restaurant_id = request.form["restaurant_id"]
    restaurant_id_hash = request.form["h"]
    valid_hash_supplied(restaurant_id, restaurant_id_hash)
    restaurant = restaurant_from_cache(cache, int(restaurant_id), restaurant_svc)

    form: ReservationForm = ReservationForm(request.form)
    if not form.validate():
        # some of the model-validation did not work out, show the form again!
        return render_template("reservation/partial/reservation_form.html", restaurant=restaurant, form=form)

    try:
        reservation = reservation_svc.reserve(
            ReservationRequestModel(
                restaurant_id=int(restaurant_id),
                name=form.name.data,
                num_people=form.num_people.data,
                time_from=form.time_from.data,
                time_until=form.time_until.data,
                reservation_date=form.reservation_date.data,
            )
        )
    except ReservationError as res_error:
        LOG.info(f"could not place a reservation '{res_error}'")
        # show the form again and display the reason for not being able to place reservation
        return render_template(
            "reservation/partial/reservation_form.html", restaurant=restaurant, form=form, reservation_error=res_error
        )

    LOG.info(f"create a reservation for '{reservation.name}' on the '{reservation.reservation_date}'")

    # fetch the reservations again
    reservations = reservation_svc.get_reservation_for_restaurant(restaurant_id)
    LOG.debug(f"got {len(reservations)} reservations")
    return render_template("reservation/partial/reservation.html", reservations=reservations, restaurant=restaurant)


@bp.delete("/reservation/partial/<restaurant_id>/<reservation_id>")
@login_required
@inject
def delete(
    restaurant_id: int,
    reservation_id: int,
    restaurant_svc: RestaurantService = Provide[Container.restaurant_svc],
    reservation_svc: ReservationService = Provide[Container.reservation_svc],
    cache: Cache = Provide[Container.cache],
):
    restaurant = restaurant_from_cache(cache, int(restaurant_id), restaurant_svc)

    try:
        reservation_svc.delete(reservation_id)
        reservations = reservation_svc.get_reservation_for_restaurant(restaurant_id)
        LOG.debug(f"got {len(reservations)} reservations")
        return render_template(
            "reservation/partial/reservation.html", reservations=reservations, restaurant=restaurant
        )
    except Exception as e:
        LOG.error(f"could not delete reservation '{e}'")

        LOG.error(f"could not delete reservation '{e}'")

src/restaurant_app/templates/reservation/partial/component_reservation_table.html
<table class="table table-bordered table-hover" id="reservation_list">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Date</th>
      <th scope="col">Name</th>
      <th scope="col">Guests</th>
      <th scope="col">Time</th>
      <th scope="col">Table</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for r in reservations %}
    <tr>
      <th scope="row">{{ r.number }}</th>
      <td>{{ r.date_format() }}</td>
      <td>{{ r.name }}</td>
      <td>{{ r.num_people }}</td>
      <td>{{ r.reservation_time_format() }}</td>
      <td>{{ r.reserved_table.number }} ({{ r.reserved_table.places }})</td>
      <td><a href="#"
          hx-delete="{{ url_for('reservation.delete', restaurant_id=restaurant.id, reservation_id=r.id) }}"
          hx-target="#reservation-content"
          hx-swap="outerHTML"
          hx-confirm="Are you sure you want to delete the reservation?"><i class="bi bi-trash"></i></a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>

src/restaurant_app/templates/reservation/partial/reservation.html
<div id="reservation-content" class="reservation_list">
  <div col="row">
    <div class="col align-self-end">
      <button type="button" class="btn btn-outline-primary btn-lg float-end"
      hx-get="{{ url_for('reservation.partial_reservation_form', restaurant_id=restaurant.id, h=restaurant.id_hash) }}"
      hx-target="#reservation-content" hx-swap="outerHTML"><i class="bi bi-egg-fried"></i> Create Reservation</button>
    </div>
  </div>

  <div class="row">

    <div class="col-3"></div>
    <div class="col-6 text-center">

      {% if reservations|length == 0 %}

        <div class="alert alert-primary" role="alert">
          Currently no reservations available for restaurant '{{ restaurant.name }}'
        </div>

      {% else %}

        {% include "reservation/partial/component_reservation_table.html" %}

      {% endif %}

    </div>
    <div class="col-3"></div>
  </div>

</div>

src/restaurant_app/templates/reservation/partial/reservation_form.html
<div class="container reservation_form" id="reservation_form">
  <h5>Create a reservation</h5>

  {% if reservation_error %}
    <div class="alert alert-danger" role="alert">
      <i class="bi bi-exclamation-octagon"></i> Unfortunately the reservation could not be created: <strong>{{ reservation_error }}</strong>
    </div>
    {% endif %}


  {% from "_formhelpers.html" import render_field %}
    <form class="row g-3" novalidate >
      {{ form.restaurant_id }}
      {{ form.h }}
      {{ form.csrf_token }}

      <div class="col-md-4">
        {{ render_field(form.name) }}
      </div>
      <div class="col-md-4">
        {{ render_field(form.num_people) }}
      </div>
      <div class="col-md-4">
        {{ render_field(form.reservation_date) }}
      </div>
      <div class="col-md-6">
        {{ render_field(form.time_from) }}
      </div>
      <div class="col-md-6">
        {{ render_field(form.time_until) }}
      </div>

      <div class="col-12">
        <button type="button" class="btn btn-secondary"
          hx-get="{{ url_for('reservation.partial_reservations', restaurant_id=form.restaurant_id.data) }}"
          hx-target="#reservation_form"
          hx-swap="outerHTML">Cancel</a>
        <button type="button" class="btn btn-primary float-end"
          hx-post="{{ url_for('reservation.save')}}"
          hx-target="#reservation_form"
          hx-swap="outerHTML">Reserve</button>
      </div>
    </form>
</div>