src/restaurant_app/restaurant/models.py
import enum
from dataclasses import dataclass
from typing import List


@dataclass
class AddressModel:
    street: str
    city: str
    zip: str
    country_code: str


@dataclass
class TableModel:
    id: int
    number: str
    places: int


@dataclass
class MenuModel:
    id: int
    name: str
    price: float
    category: str


class WeekDay(enum.StrEnum):
    MONDAY = "MONDAY"
    TUESDAY = "TUESDAY"
    WEDNESDAY = "WEDNESDAY"
    THURSDAY = "THURSDAY"
    FRIDAY = "FRIDAY"
    SATURDAY = "SATURDAY"
    SUNDAY = "SUNDAY"


@dataclass
class RestaurantModel:
    id: int
    id_hash: str
    name: str
    open_days: List[WeekDay]
    open_from: List[int]
    open_until: List[int]
    address: AddressModel
    tables: List[TableModel]
    menus: List[MenuModel]

    def open_from_format(self) -> str:
        return f"{self.open_from[0]:02}:{self.open_from[1]:02}"

    def open_until_format(self) -> str:
        return f"{self.open_until[0]:02}:{self.open_until[1]:02}"

    def display_open_time(self) -> str:
        return f"{self.open_from[0]:02}:{self.open_from[1]:02} - {self.open_until[0]:02}:{self.open_until[1]:02}"

    def table_count(self) -> int:
        if self.tables is None:
            return 0
        return len(self.tables)

src/restaurant_app/restaurant/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, HiddenField, SelectField, StringField, TimeField, validators

from ..shared.form_validators import Gt, Lt


class RestaurantForm(FlaskForm):
    id = HiddenField("id")
    h = HiddenField("h")
    name = StringField("Name", [validators.DataRequired(), validators.Length(max=255)])
    street = StringField("Street", [validators.DataRequired(), validators.Length(max=255)])
    city = StringField("City", [validators.DataRequired(), validators.Length(max=255)])
    zip = StringField("Zip", [validators.DataRequired(), validators.Length(max=25)])
    country = SelectField(
        "Country",
        [validators.DataRequired(), validators.Length(max=2)],
        choices=[("AT", "Austria"), ("DE", "Germany")],
    )
    open_from = TimeField(
        "Open from",
        [validators.DataRequired(), Lt("open_until", message="'Open from' needs to be before 'Open until'")],
    )
    open_until = TimeField(
        "Open until",
        [validators.DataRequired(), Gt("open_from", message="'Open until' needs to be after 'Open from'")],
    )
    open_monday = BooleanField("Monday")
    open_tuesday = BooleanField("Tuesday")
    open_wednesday = BooleanField("Wednesday")
    open_thursday = BooleanField("Thursday")
    open_friday = BooleanField("Friday")
    open_saturday = BooleanField("Saturday")
    open_sunday = BooleanField("Sunday")

src/restaurant_app/restaurant/views.py
import datetime
from ast import List

from dependency_injector.wiring import Provide, inject
from flask import Blueprint, redirect, render_template, request, url_for

from ..auth.views import login_required
from ..infrastructure.container import Container
from ..infrastructure.logger import LOG
from ..shared.errors import NotFoundError
from ..shared.hash import valid_hash, valid_hash_supplied
from ..shared.view_helpers import prepare_view_model
from .forms import RestaurantForm
from .models import AddressModel, RestaurantModel, WeekDay
from .service import RestaurantService

bp = Blueprint("restaurant", __name__)


@bp.get("/restaurants")
@login_required
@inject
def index(restaurant_svc: RestaurantService = Provide[Container.restaurant_svc]):
    LOG.info("view restaurant/index")
    restaurants = restaurant_svc.get_all()
    LOG.debug(f"get {len(restaurants)} restaurants")
    model_params = prepare_view_model(restaurants=restaurants)
    return render_template("restaurant/index.html", **model_params)


def get_time(item: List) -> datetime.time:
    return datetime.time(item[0], item[1], 0)


@bp.route("/restaurant/<restaurant_id>", methods=["GET", "POST"])
@login_required
@inject
def restaurant(restaurant_id: int, restaurant_svc: RestaurantService = Provide[Container.restaurant_svc]):
    form: RestaurantForm = None

    if request.method == "GET":
        LOG.info(f"display the restaurant details for id '{restaurant_id}'")
        valid_hash(str(restaurant_id))
        restaurant = restaurant_svc.get_by_id(restaurant_id)
        if restaurant is None:
            raise NotFoundError(f"cannot find restaurant by id '{restaurant_id}'")
        form = RestaurantForm(
            data={
                "id": restaurant.id,
                "h": restaurant.id_hash,
                "name": restaurant.name,
                "street": restaurant.address.street,
                "city": restaurant.address.city,
                "zip": restaurant.address.zip,
                "country": restaurant.address.country_code,
                "open_from": get_time(restaurant.open_from),
                "open_until": get_time(restaurant.open_until),
                "open_monday": True if (WeekDay.MONDAY in restaurant.open_days) else False,
                "open_tuesday": True if (WeekDay.TUESDAY in restaurant.open_days) else False,
                "open_wednesday": True if (WeekDay.WEDNESDAY in restaurant.open_days) else False,
                "open_thursday": True if (WeekDay.THURSDAY in restaurant.open_days) else False,
                "open_friday": True if (WeekDay.FRIDAY in restaurant.open_days) else False,
                "open_saturday": True if (WeekDay.SATURDAY in restaurant.open_days) else False,
                "open_sunday": True if (WeekDay.SUNDAY in restaurant.open_days) else False,
            }
        )

    elif request.method == "POST":
        form = RestaurantForm(request.form)
        if form.validate():
            valid_hash_supplied(restaurant_id, request.form["h"])
            open_days: List[WeekDay] = []
            if form.open_monday.data:
                open_days.append(WeekDay.MONDAY)
            if form.open_tuesday.data:
                open_days.append(WeekDay.TUESDAY)
            if form.open_wednesday.data:
                open_days.append(WeekDay.WEDNESDAY)
            if form.open_thursday.data:
                open_days.append(WeekDay.THURSDAY)
            if form.open_friday.data:
                open_days.append(WeekDay.FRIDAY)
            if form.open_saturday.data:
                open_days.append(WeekDay.SATURDAY)
            if form.open_sunday.data:
                open_days.append(WeekDay.SUNDAY)
            restaurant = RestaurantModel(
                id=int(form.id.data),
                id_hash=request.form["h"],
                name=form.name.data,
                open_from=[form.open_from.data.hour, form.open_from.data.minute],
                open_until=[form.open_until.data.hour, form.open_until.data.minute],
                address=AddressModel(
                    street=form.street.data, city=form.city.data, zip=form.zip.data, country_code=form.country.data
                ),
                open_days=open_days,
                tables=None,
                menus=None,
            )
            restaurant_svc.save(restaurant)
            return redirect(url_for("restaurant.index"))

    model_params = prepare_view_model(form=form)
    return render_template("restaurant/detail.html", **model_params)

src/restaurant_app/templates/restaurant/detail.html
{% extends '_layout.html' %}

{% block header %}
  <h1>{% block title %}Restaurant: {{ form.name.data }}{% endblock %}</h1>
{% endblock %}

{% block content %}
  <div class="container">
    <h3>Restaurant:</h3>

    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
      <i class="bi bi-exclamation-octagon"></i> Could not procede because of validation errors!
    </div>
    {% endif %}

    {% from "_formhelpers.html" import render_field, render_select_field, render_checkbox_field %}
    <form class="row g-3" novalidate action="{{ url_for('restaurant.restaurant', restaurant_id=form.id.data, h=form.h.data)}}" method="POST">
      {{ form.id }}
      {{ form.h }}
      {{ form.csrf_token }}

      <div class="col-md-12">
        {{ render_field(form.name) }}
      </div>
      <div class="col-md-5">
        {{ render_field(form.street) }}
      </div>
      <div class="col-md-1">
        {{ render_field(form.zip) }}
      </div>
      <div class="col-md-4">
        {{ render_field(form.city) }}
      </div>
      <div class="col-md-2">
        {{ render_select_field(form.country) }}
      </div>
      <div class="col-md-2">
        {{ render_field(form.open_from) }}
      </div>
      <div class="col-md-2">
        {{ render_field(form.open_until) }}
      </div>
      <div class="col-md-12">
        <label class="form-label" >Open days</label>
        {{ render_checkbox_field(form.open_monday) }}
        {{ render_checkbox_field(form.open_tuesday) }}
        {{ render_checkbox_field(form.open_wednesday) }}
        {{ render_checkbox_field(form.open_thursday) }}
        {{ render_checkbox_field(form.open_friday) }}
        {{ render_checkbox_field(form.open_saturday) }}
        {{ render_checkbox_field(form.open_sunday) }}
      </div>


      <div class="col-12">
        <a href="/restaurants" class="btn btn-secondary" role="button">Cancel</a>
        <button type="submit" class="btn btn-primary float-end">Save</button>
      </div>
    </form>
  </div>

{% endblock %}

src/restaurant_app/templates/restaurant/index.html
{% extends '_layout.html' %}

{% block header %}
  <h1>{% block title %}Restaurants{% endblock %}</h1>
{% endblock %}

{% block content %}
  <h3>List of restaurants

    <button type="button" class="btn btn-primary restaurant-add-btn">
        + Add Restaurant
    </button>

  </h3>



  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Address</th>
        <th scope="col">Open</th>
        <th scope="col">Tables</th>
      </tr>
    </thead>
    <tbody>
      {% for r in restaurants %}
      <tr>
        <th scope="row">{{ loop.index }}</th>
        <td><a href="{{ url_for('restaurant.restaurant', restaurant_id=r.id, h=r.id_hash)}}">{{ r.name }}</a></td>
        <td>{{ r.address.street }}, {{ r.address.zip }} {{ r.address.city }}, {{ r.address.country_code }}</td>
        <td>{{ r.display_open_time() }}</td>
        <td>{{ r.table_count() }}</td>
      </tr>
    </tbody>
    {% endfor %}
  </table>

{% endblock %}