src/restaurant_app/reservation/views.py
from dependency_injector.wiring import Provide, inject
from flask import Blueprint, render_template, request

from ..auth.views import login_required
from ..infrastructure.cache import Cache
from ..infrastructure.container import Container
from ..infrastructure.logger import LOG
from ..restaurant.models import RestaurantModel
from ..restaurant.service import RestaurantService
from ..shared.hash import valid_hash_supplied
from ..shared.view_helpers import get_restaurants_from_cache, prepare_view_model, put_restaurants_to_cache
from .forms import ReservationForm
from .models import ReservationRequestModel
from .service import ReservationError, ReservationService

bp = Blueprint("reservation", __name__)


def restaurant_from_cache(cache: Cache, restaurant_id: int, restaurant_svc: RestaurantService) -> RestaurantModel:
    restaurants = get_restaurants_from_cache(cache)
    if restaurants is None or len(restaurants) == 0:
        # reload restaurant from DB
        restaurants = restaurant_svc.get_all()
        if restaurants is not None and len(restaurants) > 0:
            put_restaurants_to_cache(cache, restaurants)
        restaurant = restaurant_svc.get_by_id(restaurant_id)
    else:
        restaurant = next(filter(lambda x: x.id == restaurant_id, restaurants))
    return restaurant


@bp.get("/reservation")
@login_required
@inject
def index(
    restaurant_svc: RestaurantService = Provide[Container.restaurant_svc], cache: Cache = Provide[Container.cache]
):
    LOG.info("view reservation/index")
    restaurants = restaurant_svc.get_all()
    LOG.debug(f"got {len(restaurants)} restaurants")
    if restaurants is not None and len(restaurants) > 0:
        put_restaurants_to_cache(cache, restaurants)

    model_params = prepare_view_model(restaurants=restaurants)
    return render_template("reservation/index.html", **model_params)


@bp.get("/reservation/partial/~reservations")
@login_required
@inject
def partial_reservations(
    restaurant_svc: RestaurantService = Provide[Container.restaurant_svc],
    reservation_svc: ReservationService = Provide[Container.reservation_svc],
    cache: Cache = Provide[Container.cache],
):
    LOG.info("view reservation/partial_reservations")
    restaurant_id = request.args.get("restaurant_id", "")
    if restaurant_id is None or restaurant_id == "":
        return ""

    restaurant = restaurant_from_cache(cache, int(restaurant_id), restaurant_svc)
    reservations = reservation_svc.get_reservation_for_restaurant(restaurant_id)
    LOG.debug(f"got {len(reservations)} reservations")
    return render_template("reservation/partial/reservation.html", reservations=reservations, restaurant=restaurant)


@bp.get("/reservation/partial/~reservation-form")
@login_required
@inject
def partial_reservation_form(
    restaurant_svc: RestaurantService = Provide[Container.restaurant_svc], cache: Cache = Provide[Container.cache]
):
    LOG.info("view reservation/partial_reservation_form")
    restaurant_id = request.args.get("restaurant_id", "")
    restaurant_id_hash = request.args.get("h", "")
    valid_hash_supplied(restaurant_id, restaurant_id_hash)

    restaurant = restaurant_from_cache(cache, int(restaurant_id), restaurant_svc)
    form = ReservationForm(data={"restaurant_id": restaurant_id, "h": restaurant_id_hash})
    return render_template("reservation/partial/reservation_form.html", restaurant=restaurant, form=form)


@bp.post("/reservation/partial/~reservation-save")
@login_required
@inject
def save(
    restaurant_svc: RestaurantService = Provide[Container.restaurant_svc],
    reservation_svc: ReservationService = Provide[Container.reservation_svc],
    cache: Cache = Provide[Container.cache],
):
    restaurant_id = request.form["restaurant_id"]
    restaurant_id_hash = request.form["h"]
    valid_hash_supplied(restaurant_id, restaurant_id_hash)
    restaurant = restaurant_from_cache(cache, int(restaurant_id), restaurant_svc)

    form: ReservationForm = ReservationForm(request.form)
    if not form.validate():
        # some of the model-validation did not work out, show the form again!
        return render_template("reservation/partial/reservation_form.html", restaurant=restaurant, form=form)

    try:
        reservation = reservation_svc.reserve(
            ReservationRequestModel(
                restaurant_id=int(restaurant_id),
                name=form.name.data,
                num_people=form.num_people.data,
                time_from=form.time_from.data,
                time_until=form.time_until.data,
                reservation_date=form.reservation_date.data,
            )
        )
    except ReservationError as res_error:
        LOG.info(f"could not place a reservation '{res_error}'")
        # show the form again and display the reason for not being able to place reservation
        return render_template(
            "reservation/partial/reservation_form.html", restaurant=restaurant, form=form, reservation_error=res_error
        )

    LOG.info(f"create a reservation for '{reservation.name}' on the '{reservation.reservation_date}'")

    # fetch the reservations again
    reservations = reservation_svc.get_reservation_for_restaurant(restaurant_id)
    LOG.debug(f"got {len(reservations)} reservations")
    return render_template("reservation/partial/reservation.html", reservations=reservations, restaurant=restaurant)


@bp.delete("/reservation/partial/<restaurant_id>/<reservation_id>")
@login_required
@inject
def delete(
    restaurant_id: int,
    reservation_id: int,
    restaurant_svc: RestaurantService = Provide[Container.restaurant_svc],
    reservation_svc: ReservationService = Provide[Container.reservation_svc],
    cache: Cache = Provide[Container.cache],
):
    restaurant = restaurant_from_cache(cache, int(restaurant_id), restaurant_svc)

    try:
        reservation_svc.delete(reservation_id)
        reservations = reservation_svc.get_reservation_for_restaurant(restaurant_id)
        LOG.debug(f"got {len(reservations)} reservations")
        return render_template(
            "reservation/partial/reservation.html", reservations=reservations, restaurant=restaurant
        )
    except Exception as e:
        LOG.error(f"could not delete reservation '{e}'")

        LOG.error(f"could not delete reservation '{e}'")

src/restaurant_app/templates/_formhelpers.html
{% macro render_field(field) %}
  {{ field.label(class="form-label") }}
  {% if field.errors %}
    {{ field(class="form-control error_input")}}
    <div class="invalid-feedback" style="display:block">
      {% for error in field.errors %}{{ error }}{% endfor %}
    </div>
  {% else %}
    {{ field(class="form-control ")}}
  {% endif %}
{% endmacro %}

{% macro render_select_field(field) %}
  {{ field.label(class="form-label") }}
  {% if field.errors %}
    {{ field(class="form-select error_input")}}
    <div class="invalid-feedback" style="display:block"></div>
      {% for error in field.errors %}{{ error }}{% endfor %}
    </div>
  {% else %}
    {{ field(class="form-select ")}}
  {% endif %}
{% endmacro %}

{% macro render_checkbox_field(field) %}
<div class="form-check">
  {% if field.errors %}
    {{ field(class="form-check-input error_input")}}
    <div class="invalid-feedback" style="display:block">
      {% for error in field.errors %}{{ error }}{% endfor %}
    </div>
  {% else %}
    {{ field(class="form-check-input")}}
  {% endif %}
  {{ field.label(class="form-check-label") }}
</div>
{% endmacro %}

src/restaurant_app/templates/_layout.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>

    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='img/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='img/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='img/favicon-16x16.png') }}">

    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/bootstrap-icons.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/custom.css') }}" rel="stylesheet">
  </head>
  <body>
    <main >
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Fifth navbar example">
        <div class="container-fluid">
          <a class="navbar-brand" href="#"><i class="bi bi-database"></i> Restaurant Management System</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarsExample05">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{{ url_for('restaurant.index') }}">Restaurants</a>
              </li>
              <li class="nav-item"></li>
                <a class="nav-link" aria-current="page" href="{{ url_for('reservation.index') }}">Reservation</a>
              </li>
              <!--<li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>-->
            </ul>

            <!-- use this for htmx "ajax" calls -->
            <div id="indicator" class="htmx-indicator request_indicator">
              <div class="spinner-border text-light" role="status">
                <span class="visually-hidden">Loading...</span>
              </div>
            </div>

            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="bi bi-person-circle"></i>&nbsp;{{ user.display_name }}
              </button>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item"><i class="bi bi-envelope-at"></i> {{ user.email }}</a></li>
                {% if dbtype == "sqlite" %}
                  <li><a class="dropdown-item"><img height="35" src="{{ url_for('static', filename='img/sqlite.svg') }}" /> using <strong>SQLite</strong></a></li>
                {% endif %}
                {% if dbtype == "mariadb" %}
                  <li><a class="dropdown-item"><img height="25" src="{{ url_for('static', filename='img/mariadb.svg') }}" /> using <strong>MariaDB</strong></a></li>
                {% endif %}
                <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">Logout</a></li>
              </ul>
            </div>

          </div>
        </div>
      </nav>

      <!-- content goes here -->
      <div class="container-fluid">
        {% block content %}{% endblock %}
      </div>
      <!-- end of content block -->

      <script src="{{ url_for('static', filename='js/htmx.min.js') }}"></script>
      <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
      <script src="{{ url_for('static', filename='js/sweetalert.js') }}"></script>
      <script type="text/javascript">

          // Example starter JavaScript for disabling form submissions if there are invalid fields
          (() => {
          'use strict'

          // Fetch all the forms we want to apply custom Bootstrap validation styles to
          const forms = document.querySelectorAll('.needs-validation')

          // Loop over them and prevent submission
          Array.from(forms).forEach(form => {
              form.addEventListener('submit', event => {
              if (!form.checkValidity()) {
                  event.preventDefault()
                  event.stopPropagation()
              }

              form.classList.add('was-validated')
              }, false)
          })
          })()

      </script>
      <script>
        // @found: https://htmx.org/examples/confirm/
        document.addEventListener("htmx:confirm", function(e) {
          // The event is triggered on every trigger for a request, so we need to check if the element
          // that triggered the request has a hx-confirm attribute, if not we can return early and let
          // the default behavior happen
          if (!e.srcElement.hasAttribute('hx-confirm')) return

          // This will prevent the request from being issued to later manually issue it
          e.preventDefault()

          Swal.fire({
            title: "Please confirm",
            text: `${e.detail.question}`,
            icon: "question",
            showCancelButton: true,
            confirmButtonColor: "#198754"
          }).then(function(result) {
            if (result.isConfirmed) {
              // If the user confirms, we manually issue the request
              e.detail.issueRequest(true); // true to skip the built-in window.confirm()
            }
          })
        })
      </script>
    </main>
  </body>
</html>